# Site settings
title: forecasting stock volatility
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://laragervaise.github.io/forecasting-stock-volatility/" # the base hostname & protocol for your site

twitter_username:
github_username: laragervaise

# Build settings
markdown: kramdown
